### PR TITLE
Modernize the player a bit

### PR DESCRIPTION
**Pull request by ptomato**
Gives the player a nice new-style titlebar and an app menu. Removes all the pre-GTK3 widgets that were still in our UI file.

### CODE REVIEW

**Comment by ptomato** [comment]
@wmvanvliet Here's are some more improvements to the player for you to try out!

**Comment by wmvanvliet** [comment]
I'm sure it's very fancy, but maybe a little too fancy? At work, we're on Ubuntu LTS which runs on gtk 3.10

```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17
DISTRIB_CODENAME=qiana
DISTRIB_DESCRIPTION="Linux Mint 17 Qiana"
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by ptomato** [comment]
@wmvanliet I'm starting to pick this up again! That Ubuntu LTS is now out of long-term support so I'm assuming you run something newer at work now :stuck_out_tongue_winking_eye:

**Comment by wmvanvliet** [comment]
Yeah, I'm on 16.04 now. 👴 So modern!

**Comment by wmvanvliet** [comment]
Compiling runs smoothly. Running gives:

```
(chimara:3300670): Gtk-ERROR **: 09:01:59.851: failed to add UI:
.:4:6043 Invalid property: GtkScrolledWindow.propagate_natural_width
```

**Comment by ptomato** [comment]
I see, we have to remove that property from the UI file as it requires GTK 3.22, I'll take a look at it later.

**Comment by wmvanvliet** [comment]
I went over to IT and they upgraded me to 18.04 LTS. The chimara player now starts. And looks beautiful! Wow, GTK has come a long way. Unfortunately, the player cannot find the interpreter libs (frotz/nitfol/gluxe). I've installed things into `~/.local` and added `~/.local/lib` and `~/.local/lib/chimara` to my `LD_LIBRARY_PATH`. Where is the player looking?

**Comment by ptomato** [comment]
It should be defined as `$libdir/chimara` which would be `~/.local/lib/chimara` if you configured with `--prefix=$HOME/.local`. Although possibly the newer system builds things multi-architecture by default which might put it in `~/.local/lib/x86_64-linux-gnu/chimara`.

**Comment by ptomato** [comment]
I'd suggest doing any further testing on #55, I fixed some crashes there, let me know if it works for you :smile:

**Comment by wmvanvliet** [comment]
hang on, could it be because I don't have `gobject-introspection`? `./configure` checks for it, doesn't find it, and happily continues.

**Comment by ptomato** [comment]
Probably that's not the problem, gobject-introspection _should_ be optional...

**Pull request merged**
