### PR TITLE
Remove action groups

### PR DESCRIPTION
**Pull request by ptomato**
Removes the last deprecated GTK usages from the player. This is another step towards fixing #11.

### CODE REVIEW

**Comment by ptomato** [comment]
Hey @wmvanvliet does this branch work for you? I still want to improve it a bit more by making a more modern interface with fewer menus... but this should at least work like what we had already.

**Comment by wmvanvliet** [comment]
```
(lt-chimara:20182): Gtk-ERROR **: failed to add UI: <resource>/org/chimara-if/player/chimara.ui:31:8299 <object> requires attribute "id"
Trace/BPT trap
```

**Comment by ptomato** [comment]
Too bad, a newer version of Glade doesn't add those `id` elements that are required for old versions of GTK ... try this one.

**Comment by wmvanvliet** [comment]
this one works fine.

**Pull request merged**
